# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[zh]
 languageCode = "zh-Hans"
 contentDir = "content/zh"
 title = "徐振江实验室"
 [zh.params]
   description = "徐振江实验室"
 [[zh.menu.main]]
   name = "首页"
   url = "#research"
   weight = 1
 [[zh.menu.main]]
  name = "成员"
  url = "#people"
  weight = 30

 [[zh.menu.main]]
  name = "论文"
  url = "#publications"
  weight = 40

 [[zh.menu.main]]
  name = "博客"
  url = "#posts"
  weight = 45

 [[zh.menu.main]]
  name = "活动"
  url = "#slider"
  weight = 50

 [[zh.menu.main]]
  name = "联系我们"
  url = "#contact"
  weight = 60
